settings:
  dual_pass:
    enabled: true
    wait_duration: 1s
  issue_comments:
    enabled: false
  issue_transitions:
    enabled: true
users:
  acaloiaro:
    settings:
      issue_comments:
        enabled: true
      issue_transitions:
        enabled: false
