---
'on':
  push:

name: Test
jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - name: Run
        uses: cedrickring/golang-action@1.3.0
